{{ define "discord" }}

<div class='panel panel-success'>
	<div class="panel-heading"><h3 class="panel-title"><span class="glyphicon glyphicon-user"></span>&nbsp; Chat</h3></div>
	<div class="panel-body" style='padding-top: 0; text-align: center;'>
		<a href='https://discord.gg/Kc77A9Ynps'><img src='/images/discord.png' width='200'></a>
	</div>
	<div class="panel-footer">
		<a href='https://discord.gg/Kc77A9Ynps'><span class='glyphicon glyphicon-bullhorn'></span>&nbsp; Talk with your fellow translators here</a>
	</div>
</div>

{{ end }}