{{ define "github" }}

<div class='panel panel-success'>
	<div class="panel-heading"><h3 class="panel-title"><span class="glyphicon glyphicon-pencil"></span>&nbsp; Open Source</h3></div>
	<div class="panel-body" style='padding: 1em; text-align: center;'>
		<a href='https://github.com/dyslexic-charactersheets'><img src='/images/github-logo.png' width='240'></a>
	</div>
	<div class="panel-footer">
		<a href='https://github.com/dyslexic-charactersheets/lib-charactersheets'><span class='glyphicon glyphicon-folder-open'></span>&nbsp; Library</a>
		(Pathfinder 2+)
	</div>
	<div class="panel-footer">
		<a href='https://github.com/dyslexic-charactersheets/pages'><span class='glyphicon glyphicon-folder-open'></span>&nbsp; Pages</a>
		(Pathfinder 1 and D&D 3.5)
	</div>
	<div class="panel-footer">
		<a href='https://github.com/dyslexic-charactersheets/iconics'><span class='glyphicon glyphicon-folder-open'></span>&nbsp; Iconics</a>
	</div>
	<div class="panel-footer">
		<a href='https://github.com/dyslexic-charactersheets/assets'><span class='glyphicon glyphicon-folder-open'></span>&nbsp; Assets</a>
	</div>
	<div class="panel-footer">
		<a href='https://github.com/dyslexic-charactersheets/website-new'><span class='glyphicon glyphicon-folder-open'></span>&nbsp; Website</a>
		(new site)
	</div>
	<div class="panel-footer">
		<a href='https://github.com/dyslexic-charactersheets/translator'><span class='glyphicon glyphicon-folder-open'></span>&nbsp; Translator</a>
		(this site)
	</div>
</div>

{{ end }}